import { CardChartData } from "../types/account.types";

export const combinedChartData: CardChartData[] = [
  {
    displayName: "SOL",
    trend: "up",
    trendRate: 23,
    startColor: "#121261",
    stopColor: "#407CFF",
    type: "linear",
    money: 204,
    chartData: [
      { month: "January", desktop: 0 },
      { month: "February", desktop: 30 },
      { month: "March", desktop: 10 },
      { month: "April", desktop: 50 },
      { month: "May", desktop: 30 },
      { month: "June", desktop: 70 },
      { month: "July", desktop: 30 },
    ],
  },
  {
    displayName: "ETH",
    trend: "up",
    trendRate: 12,
    startColor: "#A60040",
    stopColor: "#FF9E36",
    type: "natural",
    money: 1264,
    chartData: [
      { month: "January", desktop: 0 },
      { month: "February", desktop: 80 },
      { month: "March", desktop: 30 },
      { month: "April", desktop: 150 },
      { month: "May", desktop: 100 },
      { month: "June", desktop: 206 },
      { month: "July", desktop: 150 },
    ],
  },
  {
    displayName: "BTC",
    trend: "down",
    trendRate: 3,
    startColor: "#040075",
    stopColor: "#FF0062",
    type: "linear",
    money: 88495,
    chartData: [
      { month: "January", desktop: 0 },
      { month: "February", desktop: 30 },
      { month: "March", desktop: 10 },
      { month: "April", desktop: 50 },
      { month: "May", desktop: 30 },
      { month: "June", desktop: 70 },
      { month: "July", desktop: 30 },
    ],
  },
  {
    displayName: "USDT",
    trend: "up",
    trendRate: 9,
    startColor: "#00C851",
    stopColor: "#33ffcc",
    type: "step",
    money: 1.01,
    chartData: [
      { month: "January", desktop: 0 },
      { month: "February", desktop: 30 },
      { month: "March", desktop: 10 },
      { month: "April", desktop: 50 },
      { month: "May", desktop: 30 },
      { month: "June", desktop: 70 },
      { month: "July", desktop: 30 },
    ],
  },
  {
    displayName: "USDT",
    trend: "up",
    trendRate: 9,
    startColor: "#00C851",
    stopColor: "#33ffcc",
    type: "step",
    money: 1.01,
    chartData: [
      { month: "Day 1", desktop: 5 },
      { month: "Day 2", desktop: 15 },
      { month: "Day 3", desktop: 3 },
      { month: "Day 4", desktop: 13 },
      { month: "Day 5", desktop: 30 },
      { month: "Day 6", desktop: 11 },
      { month: "Day 7", desktop: 35 },
      { month: "Day 8", desktop: 30 },
      { month: "Day 9", desktop: 25 },
      { month: "Day 10", desktop: 24 },
      { month: "Day 11", desktop: 40 },
      { month: "Day 12", desktop: 30 },
      { month: "Day 13", desktop: 40 },
      { month: "Day 14", desktop: 10 },
      { month: "Day 15", desktop: 40 },
    ],
  },
];
